# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Wed, 21 Feb 2024 10:41:12 +0000
*               @ALL          0
*               @user         8
