<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: serg
 * Date: Thu, 22 Feb 2024 15:23:22 +0000
 */

$conf['title'] = 'Wiki';
$conf['lang'] = 'ru';
$conf['template'] = 'argon';
$conf['license'] = '';
$conf['breadcrumbs'] = 0;
$conf['youarehere'] = 1;
$conf['showuseras'] = 'username';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
