# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Wed, 21 Feb 2024 10:41:12 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

serg:$2y$10$KiLGVygCJTzGGZAQpDx0vOURwzHlXO57JH8f/lXfYIG6XHVzTgqCm:Serhii:sis.workin@gmail.com:admin,user
