version: '3.8'

services:
  3proxy:
    image: ghcr.io/tarampampam/3proxy:latest
    ports:
      - "3128:3128/tcp"
      - "1080:1080/tcp"
    environment:
      - PROXY_LOGIN= #LOGIN
      - PROXY_PASSWORD= # PASSWORD
      - PRIMARY_RESOLVER=8.8.8.8
    restart: unless-stopped

